[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32dev
framework = arduino
lib_deps =
  madhephaestus/ESP32Encoder @ ^0.11.7
  br3ttb/PID @ ^1.2.1
  sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library @ ^1.3.2
monitor_speed = 115200
build_flags = 
    -D ICM_20948_USE_DMP